### ISSUE TITLE
OpenMPP-UI: Display and update information about a running mpijob in the openm UI. Remove openm-uat namespace restriction. Enable running mpijobs for models outside default bin directory.

### ISSUE THREAD

**Issue by jacek-dudek** [StatCan/openmpp#14]
Epic https://github.com/StatCan/openmpp/issues/2
Relates to https://github.com/StatCan/openmpp/issues/8

In the current solution I use a kubectl wait command to monitor the job but I don't think I'm referencing the mpi job correctly because I don't specify the job name in the command as it's currently written.

## Objectives

- [x] users should be able to monitor the status of their MPIJobs via the UI as they're running
- [x] the MPIjob's execution log should appear onto the UI after the job's completion without using the refresh button

### Real-Time Monitoring

<Investigation and implementation Details here>

### Status Update on Completion

<Investigation and implementation Details here>

### Other Notes
<remove if not needed>

**Comment by chuckbelisle** [comment]
Including another (big) screenshot from the ompp UI on this thread.  Scroll down to see it.
Again, this is what an end user sees when examining grid status using the current ompp UI.  It has nothing to do with Google Cloud.
This screenshot shows what an active user would see looking at their 13 active runs and their 3 queued runs.
If you look carefully, you’ll notice that 4 cores in server dc23 and 8 cores in server dc27 are busy.  Good guess that it’s an OncoSim run by another user with 12 subs which is being executed in parallel on those two servers.
Further down in the screenshot the user has expanded their active model runs to examine detail.  The user can expand any of those runs to see the progress in each of its 12 subs across the grid.
Towards the bottom of the screenshot, the user has expanded their queue to see their 3 submitted jobs which are awaiting execution.

The Status column shows “green ready” for all servers in the grid.
That’s because all servers in the grid were spun up by ompp automatically to handle this high load level.
Once the queue clears, servers will be automatically spun down by ompp (the green ready will change to something else when a server is spun down).
Servers which are spun down are virtually costless.

If a user submits jobs using an R script or whatever, they’ll display in the UI just like runs submitted through the ompp UI.

This Google Cloud instance hosts ~15 models.
Things can be set up so only selected models are visible to selected users.

BTW, Google Cloud calls these servers “16-core” but we’ve set things up to only count 8 cores per server (calling those “CPU Cores” in the screenshot), because the other 8 advertised cores in each server are hyperthreaded and add little to computational throughput for these models.  Hyperthreaded cores have a downside in this context because depending on load, using them can introduce up to a 2x increase in elapsed run time, which makes it difficult for end users to predict run completion time based on past experience.  Hyperthreaded cores are particularly unhelpful when the grid is lightly loaded (which is typical), because instead of spinning up an idle server, relatively useless hyperthreaded cores on an active server will be used instead, doubling elapsed time to complete the run.  So, we just count real computationally-capable cores in the servers in the ompp cloud config file for the site.

Anyway, let us know when you want to meet, so you can do this too! 😊
As I sketched below, there’s not much for you guys to do to get something like this up and running.
Once it’s working, you can turn your attention to incorporating user credentials in the STC environment, etc.

![Image](https://github.com/StatCan/openmpp/assets/13248342/3fba8542-87df-4c52-aec3-f03fec235bc1)

**Comment by jacek-dudek** [comment]
Started looking into how I can route some information about currently executing mpijobs using output from kubectl and routing that to the shell script and having that periodically be updated until status of the mpijob that's being watched is resolved.

**Comment by jacek-dudek** [comment]
Removed the namespace restriction from the mpijob template so that mpijob workers execute in the same namespace as the notebook server and can access model binaries in the buckets storage.

**Comment by jacek-dudek** [comment]
Submitted latest working solution for forwarding mpijob run status information to openm UI in: https://github.com/StatCan/openmpp/pull/33

**Comment by jacek-dudek** [comment]
There is a quirk in openm UI. When a run is being performed the log output may pause. This appears to happen when the standard output from the model run doesn't forward anything to display for a while. There is a button next to the model run header that restarts the auto-refresh. If user notices that the auto-refresh for that model run got toggled to the paused position, they can click the button to resume the auto-refresh process.
