### ISSUE TITLE
Evaluate VScode and OPenM++ model development plugins and other tools

### ISSUE THREAD

**Issue by chuckbelisle** [StatCan/openmpp#9]
By using our current JupyterLab image in the Dev cluster, let's eval and validate VScode as a viable IDE to develop MicroSim models and its integration with OpenM++.

The latest AAW jupyterlab-cpu image in dev/prod now includes c++ debugger and c++ extension for the built in vs code, tested following this guide: https://code.visualstudio.com/docs/cpp/config-msvc

Guide for getting started with model development: https://openmpp.org/wiki/openmpp-wiki.html#Linux-Create-and-Debug-Model

It would be useful to get an evaluation of the default notebook resources, currently the CPU request is 0.5 but can scale to 4 cores, while the memory starts at 2GB and can scale to 4GB. Is this enough for basic model development and would additional resources (on the bursting side primarily) be an advantage?

**Comment by KrisWilliamson** [comment]
Initial report.
* Models run, using both the UI and via the command line.
* Models cannot be built due to a OpenM++ header file not being found.
- * libopenm folder not on PATH
- * libopenm is located at /opt/openm/1.15.4/openm
- * A ompp specific env variable called OM_ROOT should be set by the image to be /opt/openm/1.15.4/
- * The models build after setting this env variable.

**Comment by KrisWilliamson** [comment]
File associations have to be set in VSCode.
i.e. associate *.mpp  and *.ompp files with *.cpp files
Can be set in Setting (gear icon)- Text Editor - Files - Associations
The openm wiki mentiones editing a setting.json file, but this does not seem to be an option in the installed version of VSCode.
The mpp files are found and can be opened with VSCode, so this sees to be an option for syntax highlighting.
